
title: "The Lagasse Girls"
description: "Authors of *The Gluten Free Table* and *The Lagasse Girls' Big Flavor Bold Taste and No Gluten*"
url: "www.lagassegirls.com" # the base hostname & protocol for your site

include: ['_pages']
exclude: ['readme.md','license.md','Gemfile', 'CNAME', 'bower.json', 'node_modules', 'bower_components', 'sass', 'gulpfile.js', 'package.json']
# Build settings
markdown: kramdown
permalink: pretty

production: false
google_analytics_id:
# source: content
# TODO: Set default layouts for posts, pages, and arguendo, and ipsos
sass:
  style: :compressed
  sass_dir: sass


collections:
 books:
  collection_name: "Books"
  output: true
  permalink: /:collection/:path/

defaults:
  -
   scope:
    path: ''
   values:
    layout: post
  -
   scope:
    path: "_books"
    type: _books
   values:
    layout: page
